---
# handlers file for containerRunTime
- name: Restart Docker
  command: "{{ item }}"
  with_items:
   - systemctl daemon-reload
   - systemctl restart containerd
   - systemctl enable containerd
