---
# tasks file for containerRunTime
- name: Load the br_netfilter module
  command: modprobe overlay

- name: Load the br_netfilter module
  command: modprobe br_netfilter

- name: Turn Off swap
  become: true
  command: swapoff -a

- name: Disable SWAP permanently
  replace:
    path: /etc/fstab
    regexp: '(.*swap.*)'
    replace: '#\1'

- name: Copy File for Letting iptables see bridged traffic 
  copy:
   src: files/containerd.conf
   force: no
   dest: /etc/modules-load.d/containerd.conf
   mode: '777'

- name: Copy File for Letting iptables see bridged traffic 
  copy:
   src: files/99-kubernetes-cri.conf
   force: no
   dest: /etc/sysctl.d/99-kubernetes-cri.conf
   mode: '777'

- name : Apply Config For Bridged Traffic
  command: sysctl --system

- name : Install Required Packages
  yum:
     name:
      - yum-utils 
      - device-mapper-persistent-data 
      - lvm2
     state: present

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name : Install containerd 
  yum:
     name:
      - containerd.io
     state: present

- name: Create directory for containerd
  file:
   dest: /etc/containerd
   state: directory

- name : Setup containerd -1 
  shell: |
    sudo containerd config default | sudo tee /etc/containerd/config.toml

- name : Setup containerd -2 
  shell: |
    sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

- name : Setup containerd -3 
  shell: |
    sudo systemctl restart containerd
  notify: Restart Docker

