---
# tasks file for containerRunTime
- name: Load the br_netfilter module
  command: modprobe br_netfilter

- name: Turn Off swap
  become: true
  command: swapoff -a

- name: Disable SWAP permanently
  replace:
    path: /etc/fstab
    regexp: '(.*swap.*)'
    replace: '#\1'

- name: Copy File for Letting iptables see bridged traffic 
  copy:
   src: files/k8s.conf
   force: no
   dest: /etc/sysctl.d/k8s.conf
   mode: '777'

- name : Apply Config For Bridged Traffic
  command: sysctl --system

- name : Install Required Packages
  yum:
     name:
      - yum-utils 
      - device-mapper-persistent-data 
      - lvm2
     state: present

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name : Install Docker 
  yum:
     name:
      - containerd.io-1.2.13 
      - docker-ce-19.03.11 
      - docker-ce-cli-19.03.11
     state: present

- name: Create directory for docker daemon
  file:
   dest: /etc/docker
   state: directory

- name : Setup Docker daemon
  copy:
    src: files/daemon.json
    force: no 
    dest: /etc/docker/daemon.json
    mode: '777'

- name: Setup Docker daemon - 1
  file:
   dest: /etc/systemd/system/docker.service.d
   state: directory
  notify: Restart Docker
